version: '3.7'
services:
  back:
    build: .
    restart: always
    command: bash -c "sleep 1.5m && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    imgage: postgres
