from django.conf.urls import url
from django.urls import path
from . import views
from django.conf.urls import handler404

handler404 = "food.views.handler404"

urlpatterns = [
    path("", views.index, name="index"),
    path("recipelist/", views.recipelist, name="recipelist"),
    path("recipesingle/<int:rcp>/",
        views.recipesingle,
        name="recipesingle"),
    path(
        "update_educate/<int:rcp>/",
        views.update_educate,
        name="update_educate",
    ),
    path(
        "delete_educate/<int:rcp>/",
        views.delete_educate,
        name="delete_educate",
    ),
    path("", views.recipeindex, name="recipeindex"),
    path("recipesubmit/", views.recipesubmit, name="recipesubmit"),
    path("archive/", views.archive, name="archive"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path("login_user/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("register/", views.register, name="register"),
    path("add_product/", views.add_product, name="add_product"),
    path("gauge/", views.preview_gauge, name="gauge"),
    path("not_found/", views.not_found, name="404"),
    path("compare/", views.compare, name="compare"),
    path("doctor/", views.doctor, name="doctor"),
    path("search/", views.search, name="search"),
    path("profile/", views.profile, name="profile"),
    #url(r"^company_profile$", views.company_profile, name="company_profile"),
    path("doctor_profile/", views.doctor_profile, name="doctor_profile"),
    path("health/", views.health, name="health"),
    path("educate/", views.educate, name="educate"),
    path("store/", views.store, name="store"),
    path("add_educate/", views.add_educate, name="add_educate"),
    path("list_educate/<e_type>/",
        views.list_educate,
        name="list_educate"),
    path("bloglist/", views.bloglist, name="bloglist"),
    path("blogsingle/<int:pst>/", views.blogsingle, name="blogsingle"),
    path("add_blog/", views.add_blog, name="add_blog"),
    path("edit_blog/<int:pst>/", views.edit_blog, name="edit_blog"),
    path("replay/<int:pst>/", views.replay, name="replay"),
    path("resipecomment/<int:rcp>/",
        views.recipecomment,
        name="recipecomment"),
    path("resipereplay/<int:rcp>/",
        views.recipereplay,
        name="recipereplay"),
    path("reciperating/", views.reciperating, name="reciperating"),
    path("like/", views.like, name="like"),
    path("dislike/", views.dislike, name="dislike"),
    path("recipelike/", views.recipe_like, name="recipelike"),
    path("recipedislike/", views.recipe_dislike, name="recipedislike"),
    path("eshop/add/", views.eshop_add, name="eshop_add"),
    path("eshop/product/<int:id>/", views.product, name="product"),
    path("eshop/delete/", views.eshop_delete, name="eshop_delete"),
    path("eshop/list/", views.eshop_list, name="eshop"),
    path("eshop/basket/", views.basket, name="basket"),
    path("eshop/add_to_basket/", views.add_to_basket, name="add_to_basket"),
    path("eshop/checkout/", views.checkout, name="checkout"),
    path("eshop/orders/", views.orders, name="orders"),
    path("eshop/buy/", views.buy, name="buy"),
    path("eshop/basket/buy/", views.create_order, name="create_order"),
    path("eshop/basket/to_edit/", views.to_edit, name="to_edit"),
    path("eshop/edit/<int:p>/", views.eshop_edit, name="eshop_edit"),
]
