from django.urls import URLPattern, path
from .views import *
from rest_framework.authtoken import views as rest_views

urlpatterns = [
    # ------------------------------------------------------- #
    # -------------------------USERS------------------------- #
    # ------------------------------------------------------- #
    path('login/', rest_views.obtain_auth_token, name="login"), # login API: need 2 fields ['username', 'password'] (method: POST)
    path('user/', UserList.as_view(), name="user_list"),
    path('user/<int:pk>', UserRud.as_view(), name="user_rud"),
    # ------------------------------------------------------- #
    # -------------------------POSTS------------------------- #
    # ------------------------------------------------------- #
    path("post/", PostList.as_view(), name="post_list"),
    path("post/<int:pk>", PostRud.as_view(), name='post_rud'),
    # ------------------------------------------------------- #
    # -------------------------MESSAGE----------------------- #
    # ------------------------------------------------------- #
    path("message/", MessageList.as_view(), name="message_list"),
    path("message/<int:pk>", MessageRud.as_view(), name='message_rud'),
    # ------------------------------------------------------- #
    # -------------------------COMMENT----------------------- #
    # ------------------------------------------------------- #
    path("comment/", CommentList.as_view(), name="comment_list"),
    path("comment/<int:pk>", CommentRud.as_view(), name='comment_rud'),
    # ------------------------------------------------------- #
    # -------------------------REPLAY----------------------- #
    # ------------------------------------------------------- #
    path("replay/", ReplayList.as_view(), name="replay_list"),
    path("replay/<int:pk>", ReplayRud.as_view(), name='replay_rud'),
    # ------------------------------------------------------- #
    # -----------------------ALLERGIE------------------------ #
    # ------------------------------------------------------- #
    path("allergie/", AllergieList.as_view(), name="allergie_list"),
    path("allergie/<int:pk>", AllergieRud.as_view(), name='allergie_rud'),
    # ------------------------------------------------------- #
    # ---------------------HEALTH_PROBLEM-------------------- #
    # ------------------------------------------------------- #
    path("health-problem/", HealthProblemList.as_view(), name="health_problem_list"),
    path("health-problem/<int:pk>", HealthProblemRud.as_view(), name='health_problem_rud'),
    # ------------------------------------------------------- #
    # -----------------------CATEGORIE----------------------- #
    # ------------------------------------------------------- #
    path("category/", CategorieList.as_view(), name="categorie_list"),
    path("category/<int:pk>", CategorieRud.as_view(), name='categorie_rud'),
    # ------------------------------------------------------- #
    # ----------------------SUBCATEGORY---------------------- #
    # ------------------------------------------------------- #
    path("sub-category/", SubCategoryList.as_view(), name="sub_category_list"),
    path("sub-category/<int:pk>", SubCategoryRud.as_view(), name='sub_category_rud'),
    # ------------------------------------------------------- #
    # ------------------------PRODUCT------------------------ #
    # ------------------------------------------------------- #
    path("product/", ProductList.as_view(), name="product_list"),
    path("product/<int:pk>", ProductRud.as_view(), name='product_rud'),
    # ------------------------------------------------------- #
    # ---------------------PRODUCTDETAILS------------------- #
    # ------------------------------------------------------- #
    path("product-detail/", ProductDetailList.as_view(), name="product_detail_list"),
    path("product-detail/<int:pk>", ProductDetailRud.as_view(), name='product_detail_rud'),
    # ------------------------------------------------------- #
    # --------------------------BLOG------------------------- #
    # ------------------------------------------------------- #
    path("blog/", BlogList.as_view(), name="blog_list"),
    path("blog/<int:pk>", BlogRud.as_view(), name='blog_rud'),
    # ------------------------------------------------------- #
    # -------------------------RECIPE------------------------ #
    # ------------------------------------------------------- #
    path("recipe/", RecipeList.as_view(), name="recipe_list"),
    path("recipe/<int:pk>", RecipeRud.as_view(), name='recipe_rud'),
    # ------------------------------------------------------- #
    # ---------------------RecipeComment--------------------- #
    # ------------------------------------------------------- #
    path("recipe-comment/", RecipeCommentList.as_view(), name="recipe_comment_list"),
    path("recipe-comment/<int:pk>", RecipeCommentRud.as_view(), name='recipe_comment_rud'),
    # ------------------------------------------------------- #
    # ---------------------RecipeRating--------------------- #
    # ------------------------------------------------------- #
    path("recipe-rating/", RecipeRatingList.as_view(), name="recipe_rating_list"),
    path("recipe-rating/<int:pk>", RecipeRatingRud.as_view(), name='recipe_rating_rud'),
    # ------------------------------------------------------- #
    # ------------------------PAYMENT------------------------ #
    # ------------------------------------------------------- #
    path("payment/", PaymentList.as_view(), name="payment_list"),
    path("payment/<int:pk>", PaymentRud.as_view(), name='payment_rud'),
    # ------------------------------------------------------- #
    # -----------------------ORDERLINE----------------------- #
    # ------------------------------------------------------- #
    path("order-line/", OrderLineList.as_view(), name="payment_list"),
    path("order-line/<int:pk>", OrderLineRud.as_view(), name='payment_rud'),
    # ------------------------------------------------------- #
    # -------------------------ORDER------------------------- #
    # ------------------------------------------------------- #
    path("order/", OrderList.as_view(), name="order_list"),
    path("order/<int:pk>", OrderRud.as_view(), name='order_rud'),
    # ------------------------------------------------------- #
    # -----------------------CONTACT------------------------- #
    # ------------------------------------------------------- #
    path("contact/", ContactList.as_view(), name="contact_list"),
    path("contact/<int:pk>", ContactRud.as_view(), name='contact_rud'),
    # ------------------------------------------------------- #
    # -------------------CUSTOMERPRODUCT--------------------- #
    # ------------------------------------------------------- #
    path("customer-product/", CustomerProductList.as_view(), name="customer_product_list"),
    path("customer-product/<int:pk>", CustomerProductRud.as_view(), name='customer_product_rud'),
    # ------------------------------------------------------- #
    # -------------------CUSTOMERHEALTH---------------------- #
    # ------------------------------------------------------- #
    path("customer-health/", CustomerHealthList.as_view(), name="customer_health_list"),
    path("customer-health/<int:pk>", CustomerHealthRud.as_view(), name='customer_health_rud'),
    # ------------------------------------------------------- #
    # -------------------COMMENTPRODUCT---------------------- #
    # ------------------------------------------------------- #
    path("comment-product/", CommentProductList.as_view(), name="comment_product_list"),
    path("comment-product/<int:pk>", CommentProductRud.as_view(), name='comment_product_rud'),
    # ------------------------------------------------------- #
    # -------------------PRODUCTCATEGORY--------------------- #
    # ------------------------------------------------------- #
    path("product-category/", ProductCategoryList.as_view(), name="product_category_list"),
    path("product-category/<int:pk>", ProductCategoryRud.as_view(), name='product_category_rud'),
]
