# Generated by Django 3.0.8 on 2020-09-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educate',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
