# Generated by Django 3.0.8 on 2020-09-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200914_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educate',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
    ]
