# Generated by Django 3.1 on 2022-06-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20220626_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLevel',
            fields=[
                ('name', models.CharField(choices=[('sedentary', 'Sedentary'), ('light activity', 'Light Activity'), ('moderate activity', 'Moderate Activity'), ('intense activity', 'Intense Activity')], max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('name', models.CharField(choices=[('muslim', 'Muslim'), ('christianity', 'Christianity'), ('judaism', 'Judaism')], max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
