# Generated by Django 3.1 on 2022-07-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_productart_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
